//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiBanHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPN
    {
        public int id { get; set; }
        public int ma_phieu_nhap { get; set; }
        public string ma_sp { get; set; }
        public int so_luong { get; set; }
        public decimal gia_nhap { get; set; }
        public decimal tong { get; set; }
    
        public virtual SanPham SanPham { get; set; }
        public virtual PhieuNhap PhieuNhap { get; set; }
    }
}
