//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiBanHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietHDs = new HashSet<ChiTietHD>();
            this.ChiTietPNs = new HashSet<ChiTietPN>();
        }
    
        public string ma_sp { get; set; }
        public string ma_loai { get; set; }
        public string ten_sp { get; set; }
        public string don_vi_tinh { get; set; }
        public decimal gia_sp { get; set; }
        public int thoi_gian_bh { get; set; }
        public int so_luong { get; set; }
        public string hang_san_xuat { get; set; }

        public override string ToString() => ten_sp;

        public virtual LoaiSP LoaiSP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHD> ChiTietHDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPN> ChiTietPNs { get; set; }
    }
}
